### ISSUE TITLE
RFC: Build Pipelines Design

### ISSUE THREAD

**Issue by erikh** [tinyci/ci-agents#61]
A proposal for build pipelines. To define them, we will use this definition:

> A build pipeline is responsible for creating an artifact suitable for running
> tests with. Tests are responsible for triggering the build before the test,
> hence establishing a pipeline where by if the build fails, the test fails
> too.

To be pedantic, this establishes a few rules:

- Test states are logically AND-ed with the build state. Builds must succeed, or the tests fail.
- Tests are responsible for triggering the build, meaning that diff selection
  -- not a static configuration -- should be necessary for determining what to
  build.
- The artifact must go somewhere between the build and test runs.
- In an ideal scenario, there should be no difference between a build and test
  as far as the CI system is concerned; only that a build is triggered before a
  test.
- Runners should be responsible for distribution of assets.

## Asset management

While most other things in this document can be logically concluded from prior
designs; asset management is a poorly-addressed issue on this subject.

Assets may be:

- tarballs
- docker images
- vm images
- PNG images (had to, sorry; but it's true)
- compiled binaries or other similar binary content

This doesn't leave a ton of room on how to actually _deal_ with these different
types of assets. Further thought on how the current `assetsvc` is architected
makes me think that instead of making the `assetsvc` bigger, perhaps we should
just make it easier to leverage in multiple ways.

### Introduction to the asset router

The asset router is a proxy or redirect (not sure yet, advantages and
disadvantages to both) service that allows runners to talk to it to get
configuration resources based on the _asset type_. The resources are arguably
arbitrary and reserved for runners.

Runners will specifically ask for a pre-defined _content type_ (which is not a
MIME type, just a name) and the name of the resource from the asset router; for
example `docker|golang`. It will not be a syntax; marshalled GRPC structs. The
service will then point at _another service_ by way of returning a
configuration blob. For our current uses, that looks like one of the following
options:

- docker registry JSON allowing the runner to configure it
- A simple URL.

For example, if you were to request a `docker_image` content type of
`static_base_image`, it would respond with a registry configuration pointing
you to an `assetsvc` where those docker images are managed.

Since this configuration is entirely driven by the backend, secrets can be
used. This solution should allow for a simple user experience while still
allowing for much flexibility by the administrator, while totally sacrificing
the complexity of programming languages like Groovy.

Now, the `assetsvc`? It will have to be slightly rebuilt to accept:

- The associated run ID (listed for posterity, this exists)
- [ ] Association with a task ID (arguably comes from the run already, but this isn't a part of the protocol)
- [ ] Potentially unseekable binary content (right now, this limitation is because the `assetsvc` does CI logs only)
- [ ] A globally configured _content type_ tag for the assets
- [ ] A way to pull this data
  - [ ] with optional compression (https://github.com/klauspost/pgzip).

## Queue changes

The queue management was the hardest part for me to figure out. Our queuing
system is quite simple right now and very performant, something I'm loathe to
change too much.

The fundamental performance win from our queue system comes from two features:

- postgres is quite fast, and we have a very fast way to get the first item in the queue atomically
- our queueing system current assumes the first item in the queue is the next item to be sent to runners

This avoids all sorts of ugly graph traversal problems which we're about to
introduce with build pipelines. So.

If we make runs dependent on other runs in linked-list fashion, we get the
above graph for free. We can seek backwards through time to find the state of
those runs, and cancel or fail them if dependencies also failed, skipping test
cycles that were going to fail anyway.

This is kind of hard to do in most SQL engines and usually requires N queries;
but PostgreSQL has the notion of "recursive CTEs" or basically recursion in SQL
queries that we could leverage. I've also modeled linked lists in SQL by
performing self-joins on the table with interesting results at times (the query
optimizer does not like it, usually, but we'll need to measure).

Side note and unrelated to this ticket: This may be a good case for pulling
this logic out of postgres and `datasvc` entirely and opting for something like
redis or etcd (really not sure about this choice) to manage the queue. It would
be a sane architectural decision from a "it's easier to replace datasvc this
way" standpoint.

As for managing the actual submission _into the queue_, we can trivialize this
at configuration management time; if the tests depend on an asset that is built
by a build, that build _will be queued automatically, and the test will be added
as a dependency_. If the build is already queued for the repository/sha
combination; _then only the test is given the build as a dependency, assuming it
will complete_.

This allows diff selection to be performed _before analyzing the build
lifecycle_ and thusly saving a lot of building in the process for those
situations where the build is not required. Also, builds tend to be more
complicated than just a test run definition, and it will be nice to leave them
in the repo without having to worry about them wasting resources.

The dependency system also completely ignores queues which is good, so builds
can run on a faster/specialized set of instances and tests can run in a more
global pool that leverages the builds.

- [ ] Add dependencies to test runs with appropriate query mech
- [ ] Add selection of build(s) based on required assets
- [ ] Add cancel logic for failed dependencies

## Configuration items

Two forms of configuration live within tinyCI -- the _task definition_
(`task.yml`) and the _repository definition_ (`tinyci.yml`). It makes a lot of
sense to carry this syntax similarly in both files, as most users will want to
configure a small amount of builds and lots of tests to run against them; it
may make more sense for simplification's sake to store these build
configurations globally.

This also deprecates the "image" parameter in runs, in favor of the above asset
tag system. Images are still present in builds; it's just the runner's job to
determine what a image is now, which was always the case, but not as free-form
as it is now.

The syntax will look something like this:

```yaml
builds:
  foo:
    queue: buildFoos
    command: ['do', 'a', 'build']
    assets:
      - type: docker_image
        name: static_base_image
    generates:
      - type: docker_image
        # will be dynamically tagged after the fact, but be associated with
        # `foo` for the task. See queue stuff below.
        name: foo
  bar:
    queue: buildBars
    command: ['do', 'a', 'fs', 'build']
    assets:
      type: tarball
      name: build # different build, different overall tag.
runs:
  fooRun:
    queue: runFoos # different queues for build and test are entirely reasonable, more below
    command: ['run', 'a', 'test']
    assets:
      - type: docker_image
        name: foo
  testBuildTar:
    queue: runBars
    # let's assume the runner used on this queue creates this file before the run starts.
    command: ['tar', 'vxzf', 'build.tar.gz']
    assets:
      - type: docker_image
        name: foo
      - type: tarball
        name: build
```

- [ ] Global and Local Build Configuration
- [ ] Build syntax (YAML structs) and validation

## Conclusion

Comments are very welcome but I would like to keep our focus:

- Stay within the existing ecosystem if possible
- PLs, inline queue manip and other non-deterministic behavior is not really what I think we need; so let's avoid that discussion

I think this will overall be a net positive and I think it will take a week or
two to get a MVP and then maybe a few more weeks to shake the bugs out.
